### ISSUE TITLE
Uncaught TypeError: this.treeView.before is not a function

### ISSUE THREAD

**Issue by amandeepmittal** [lixinliang/tree-view-search-bar#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.1
**Thrown From**: [tree-view-search-bar](https://github.com/lixinliang/tree-view-search-bar) package 0.1.3

### Stack Trace

Uncaught TypeError: this.treeView.before is not a function

```
At /Users/amandeepmittal/.atom/packages/tree-view-search-bar/lib/view.js:54

TypeError: this.treeView.before is not a function
    at TreeViewSearchBarView.initialize (view.js:54:23)
    at TreeViewSearchBarView.create (view.js:43:18)
    at MainModel.show (main.js:177:19)
    at MainModel.set (main.js:161:34)
    at MainModel.initializePackage (main.js:139:13)
    at checkTreeViewStatus (main.js:36:30)
    at atom.project.onDidChangePaths.rootDirectories (main.js:41:25)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Project.module.exports.Project.addPath (/app.asar/src/project.js:288:29)
    at /app.asar/src/atom-environment.js:1028:40
    at /app.asar/src/application-delegate.js:31:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
     -1:11.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:27.5.0 application:add-project-folder (atom-pane.pane.active)
     -0:04.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-handlebars 1.3.0 
atom-jade 0.3.0 
atom-json-color 0.6.0 
atom-lupa 0.7.32 
atom-nodejs-snippets 1.5.0 
autoclose-html 0.23.0 
autocomplete-json 5.4.0 
badges 2.2.5 
bottom-dock 0.4.4 
busy-signal 1.3.0 
code-peek 1.4.17 
code-stats-atom 2.0.1 
expressjs 1.2.0 
file-icons 2.0.17 
filesize 2.0.4 
Handlebars 1.7.1 
highlight-line 0.12.0 
highlight-selected 0.12.0 
intentions 1.1.2 
ionic-framework-snippets 1.2.1 
ionic-preview 0.7.0 
jade 1.1.0 
linter 2.1.0 
linter-jshint 3.0.3 
linter-jsonlint 1.3.0 
linter-ui-default 1.2.1 
nodemon-generator 1.0.2 
open-recent 5.0.0 
pretty-json 1.6.1 
swackets 0.26.0 
sync-settings 0.8.1 
todo-manager 0.2.10 
tree-view-git-status 1.3.1 
tree-view-search-bar 0.1.3 
wakatime 6.0.13 
wordcount 2.10.4 
```

**Comment by lixinliang** [comment]
The API of `tree-view` probably changed.
I think this problem occurs in `Atom: 1.16.0-beta0 x64`.
I will check the specific reason later.

**Comment by amandeepmittal** [comment]
@lixinliang Yes, and looking forward to it.

**Comment by lixinliang** [comment]
[0.1.4](https://github.com/lixinliang/tree-view-search-bar/releases/tag/v0.1.4) is published.

**Comment by amandeepmittal** [comment]
👍
