### ISSUE TITLE
Uncaught TypeError: Cannot read property 'disconnect' of undefined

### ISSUE THREAD

**Issue by asci** [lixinliang/tree-view-search-bar#11]
[Enter steps to reproduce:]

1. Close `tree-view`

**Atom**: 1.17.0-beta0 x64
**Electron**: 1.3.14
**OS**: Mac OS X 10.12.4
**Thrown From**: [tree-view-search-bar](https://github.com/lixinliang/tree-view-search-bar) package 0.1.3

### Stack Trace

Uncaught TypeError: Cannot read property 'disconnect' of undefined

```
At /Users/artemrasniansky/.atom/packages/tree-view-search-bar/lib/view.js:85

TypeError: Cannot read property 'disconnect' of undefined
    at destroy (/packages/tree-view-search-bar/lib/view.js:85:26)
    at /packages/tree-view-search-bar/lib/view.js:92:17
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

### Commands

```
     -1:08.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
  2x -0:15.6.0 project-viewer:togglePanel (div.tool-panel.tree-view)
     -0:05.4.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
antialiased 0.1.0 
atom-beautify 0.29.18 
atom-clock 0.1.6 
atom-runner 2.7.1 
atom-ternjs 0.18.2 
auto-indent 0.5.0 
autocomplete-modules 1.6.9 
build 0.67.0 
build-npm-apm 0.12.0 
build-stylus 0.8.1 
busy 0.7.0 
busy-signal 1.3.0 
change-case 0.6.5 
clipboard-plus 0.5.1 
color-picker 2.2.5 
conventional-changelog 0.1.0 
docblockr 0.9.4 
elm-format 2.1.0 
emmet 2.4.3 
extract-selection 0.2.1 
file-icons 2.1.2 
flex-tool-bar 0.12.0 
font-viewer 0.3.1 
git-blame 1.0.0 
git-history 3.3.0 
git-time-machine 1.5.9 
gitignore-snippets 0.2.5 
highlight-selected 0.13.1 
hyperclick 0.0.40 
intentions 1.1.2 
js-hyperclick 1.10.1 
language-babel 2.57.2 
language-elm 1.5.0 
language-elmx 1.2.9 
language-gherkin 1.0.4 
language-graphql 0.8.0 
language-stylus 0.2.0 
language-swift 0.5.0 
lcov-info 0.12.0 
less-than-slash 0.16.0 
linter 2.1.2 
linter-eslint 8.1.5 
linter-flow 5.5.1 
linter-scss-lint 3.1.0 
linter-stylint 2.2.7 
linter-ui-default 1.2.2 
local-history 4.0.1 
merge-conflicts 1.4.4 
node-debugger 1.10.1 
nord-atom-syntax 0.8.0 
nord-atom-ui 0.11.0 
open-in-browser 0.5.0 
open-recent 5.0.0 
open-terminal-here 2.3.0 
pigments 0.39.1 
project-viewer 1.0.12 
react 0.16.2 
recent-files-fuzzy-finder 0.3.1 
rest-client 1.3.1 
run-command2 1.12.2 
script 3.14.1 
scroll-searcher 5.2.0 
sort-lines 0.14.0 
split-diff 1.3.0 
term3 0.22.1 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
tree-view-copy-relative-path 1.1.0 
tree-view-git-branch 0.1.2 
tree-view-search-bar 0.1.3 
```

**Comment by lixinliang** [comment]
Wow, `1.17.0-beta0 x64`.

This error is related to `MutationObserver`, I will mark down in my todo list and try to fix in next version.

**Comment by lixinliang** [comment]
`v1.0.0` is pulished.
It's working for `Atom` `1.21.0`.
Maybe new version could help you, if you don't mind to upgrate.
