### ISSUE TITLE
Uncaught TypeError: _this3.treeView.selectedEntry is not a function

### ISSUE THREAD

**Issue by mingsai** [lixinliang/tree-view-search-bar#13]
**Update #2** 

Error occurs only after searching for some text and then clicking any folder. If one disables the package, and clicks folders in tree-view, then the error will not occur. I have also disabled symbols-tree-view to further isolate the issue. The error does occur when using Atom safe mode (atom --safe). 

**Update #1:**

After restart and disabling tree-view-filter:

1. When selecting any folder in tree-view after searching for some text, the same base error is generated.

```
TypeError: _this3.treeView.selectedEntry is not a function
    at MutationObserver.<anonymous> (/path/to/username/.atom/packages/tree-view-search-bar/lib/view.js:65:48)
```

First. Thanks for putting out the new version. This is an extremely useful package.

Steps to reproduce:

1. I had tree-view-filter and tree-view-search-bar enabled
2. Attempt to toggle the tree-view-filter function using the menu (Packages/Tree View Filter > Toggle) and received an error from tree-view-searchbar  
3. Disabled tree-view-filter and restarted Atom to regain the search bar functionality.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [tree-view-search-bar](https://github.com/lixinliang/tree-view-search-bar) package 0.1.4

### Stack Trace

Uncaught TypeError: _this3.treeView.selectedEntry is not a function

```
At /path/to/username/.atom/packages/tree-view-search-bar/lib/view.js:65

TypeError: _this3.treeView.selectedEntry is not a function
    at /packages/tree-view-search-bar/lib/view.js:65:48)
```

### Commands

```
     -0:38.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-spacegray-atom-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
aligner 0.22.3 
android 0.1.0 
android-debugger 0.1.0 
api-docs 0.0.6 
ariake-dark-syntax 0.1.3 
atom-beautify 0.29.24 
atom-bootstrap4 1.4.0 
atom-clock 0.1.7 
atom-fuzzy-grep 0.16.0 
atom-html-preview 0.1.22 
atom-jade 0.3.0 
atom-material-syntax 1.0.6 
atom-material-ui 1.3.10 
atom-nodejs-snippets 1.5.0 
atom-notifier 0.5.1 
atom-pair 2.0.10 
atom-ternjs 0.18.3 
atom-xcode 0.1.3 
atomdocr 1.0.0 
aurora-theme 1.2.2 
auto-detect-indentation 1.3.0 
autocomplete-bash-builtins 0.3.5 
autocomplete-cmake 0.3.1 
autocomplete-haskell 0.7.2 
autocomplete-swift 1.0.3 
bottom-dock 0.4.4 
build-xcodebuild 0.2.0 
coconut 0.11.0 
compare-files 0.8.0 
dash 1.7.1 
emmet 2.4.3 
file-icons 2.1.4 
floobits 0.32.10 
git-clone 0.2.0 
git-plus 7.8.0 
git-time-machine 1.5.9 
glist 2.2.0 
grunt-runner 0.14.0 
grunt-snippets 0.1.1 
highlight-line 0.12.0 
highlight-selected 0.13.1 
Hydrogen 1.12.1 
imdone-atom 2.2.6 
imdone-atom-github 0.1.11 
ink 0.6.5 
jade 1.1.0 
jade-beautify 0.1.5 
java-generator 2.2.3 
jumpy 3.1.3 
language-cmake 0.3.0 
language-common-lisp 0.9.5 
language-dots 0.0.4 
language-latex 1.0.0 
language-lisp 0.2.0 
language-swift 0.5.0 
latex 0.43.0 
latex-autocomplete 1.0.0 
latex-completions 0.3.2 
latex-friend 0.0.11 
linter 2.1.4 
linter-bootlint 1.0.4 
linter-swift-package-manager 0.1.0 
linter-swiftc 2.0.0 
linter-swiftlint 1.2.2 
linter-write-good 0.9.0 
markdown-document 0.2.1 
markdown-preview-plus 2.4.9 
merge-conflicts 1.4.4 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
motepair 0.23.0 
motepair2 0.37.0 
node-debugger 1.10.1 
node-on-fire 0.1.0 
nord-atom-ui 0.11.0 
omnisharp-atom 0.31.2 
open-in 4.0.0 
pdf-view 0.57.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
playyoutube 1.3.0 
preview 0.17.0 
preview-inline 1.4.7 
qolor 0.4.1 
quicknote 0.1.1 
RebelChat 0.8.1 
script 3.14.1 
spacegray-atom-dark-syntax 1.3.2 
spacegray-dark-ui 0.13.0 
supercopair 0.10.7 
svg-preview 0.11.0 
swift-autocomplete-snippets 0.1.0 
swift-debugger 0.1.2 
swiftkit 0.3.0 
symbols-list 2.4.0 
symbols-tree-view 0.14.0 
terminal-plus 0.14.5 
theme-switch 0.4.0 
todo-manager 0.2.10 
tree-view-filter 0.4.1 
tree-view-search-bar 0.1.4 
turbo-javascript 1.4.0 
wakatime 7.0.2 
```

**Comment by mingsai** [comment]
Attached is a short review of the issue that I am seeing.
[0.1.4-bug-selecting-folder-after-search.zip](https://github.com/lixinliang/tree-view-search-bar/files/989562/0.1.4-bug-selecting-folder-after-search.zip)

**Comment by lixinliang** [comment]
Yep, I see.
On my way.

**Comment by lixinliang** [comment]
[0.1.7](https://github.com/lixinliang/tree-view-search-bar/releases/tag/v0.1.7) is published.
