### ISSUE TITLE
Uncaught TypeError: Cannot read property 'disconnect' of null

### ISSUE THREAD

**Issue by JoeNoPhoto** [lixinliang/tree-view-search-bar#15]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [tree-view-search-bar](https://github.com/lixinliang/tree-view-search-bar) package 0.1.8

### Stack Trace

Uncaught TypeError: Cannot read property 'disconnect' of null

```
At /Users/JoeNoPhoto/.atom/packages/tree-view-search-bar/lib/view.js:92

TypeError: Cannot read property 'disconnect' of null
    at destroy (/packages/tree-view-search-bar/lib/view.js:92:26)
    at /packages/tree-view-search-bar/lib/view.js:99:17
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -4:24.9.0 core:select-all (input.hidden-input)
     -4:24.3.0 core:copy (input.hidden-input)
     -2:06.2.0 core:select-all (input.hidden-input)
     -2:05.8.0 core:copy (input.hidden-input)
     -1:16.4.0 core:undo (div.tool-panel.tree-view)
     -0:49.6.0 tree-view:duplicate (div.tool-panel.tree-view)
  4x -0:47.2.0 editor:duplicate-lines (div.tool-panel.tree-view)
     -0:18.5.0 tree-view:toggle (div.tool-panel.tree-view)
     -0:13.9.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:11.8.0 core:undo (input.hidden-input)
  4x -0:10.9.0 tree-view:toggle (input.hidden-input)
```

### Non-Core Packages

```
apex-ui 1.0.1 
atom-beautify 0.30.5 
atom-clock 0.1.15 
atom-commander 0.10.2 
atom-dark-fusion-syntax 2.2.0 
atom-html-preview 0.2.2 
atom-ide-ui 0.4.0 
atom-ternjs 0.18.3 
atom-touch-events 0.23.0 
atom-typescript 11.0.9 
atom-wrap-in-tag 0.6.0 
autocomplete-flow 1.6.0 
autocomplete-modules 1.7.2 
browser-plus 0.0.98 
busy-signal 1.4.3 
chester-atom-syntax 0.3.0 
color-picker 2.2.5 
docblockr 0.11.0 
editorconfig 2.2.2 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
es6-javascript 1.0.0 
es6-snippets 0.3.0 
esformatter 2.3.0 
file-icons 2.1.12 
find-selection 0.16.0 
firewatch-syntax 1.1.1 
format-graphql 0.1.2 
git-history 3.3.0 
git-plus 7.9.3 
git-status 0.3.4 
git-time-machine 1.5.9 
graphql-autocomplete 1.1.1 
gruvbox-plus-syntax 1.3.1 
haskell-grammar 0.4.0 
hey-pane 1.0.0 
highlight-selected 0.13.1 
Hydrogen 1.23.0 
hyperclick 0.0.0 
ide-flowtype 0.17.4 
ide-json 0.1.0 
ide-python 0.2.1 
indent-guide-improved 1.4.13 
intentions 1.1.5 
js-hyperclick 1.11.1 
kite 0.47.0 
language-babel 2.75.1 
language-csv 1.1.2 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-pgsql 0.2.3 
language-rust 0.4.12 
language-swift 0.5.0 
language-thrift 1.0.2 
less-than-slash 0.17.0 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.3.2 
linter-flow 5.6.1 
linter-jshint 3.1.6 
linter-jsonlint 1.3.0 
linter-scss-lint 3.1.1 
linter-ui-default 1.6.10 
local-history 4.3.0 
MagicPython 1.0.12 
merge-conflicts 1.4.5 
neutron-syntax 0.7.0 
neutron-ui 0.4.0 
nucleus-dark-ui 0.12.3 
nuclide 0.258.0 
nuclide-format-js 0.0.41 
pigments 0.40.2 
prettier-atom 0.40.0 
project-manager 3.3.5 
qolor 0.4.2 
react 0.16.2 
react-es6-snippets 0.3.0 
react-es7-snippets 0.3.13 
redux-snippets 0.2.2 
restart-atom 0.2.0 
semantic-ui 1.0.9 
set-syntax 0.4.0 
slim-dark-ui 0.12.0 
sort-lines 0.15.0 
spacegray-dark-ui 0.13.0 
Sublime-Style-Column-Selection 1.7.4 
tablr 1.8.3 
tabs-to-spaces 1.0.3 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
tree-view-autoresize 2.2.0 
tree-view-git-status 1.4.0 
tree-view-search-bar 0.1.8 
zentabs 0.8.8 
```

**Comment by lixinliang** [comment]
new version is coming for `Atom: 1.21.0 x64`..
