### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '' is not a valid ...

### ISSUE THREAD

**Issue by drunkplato** [lixinliang/tree-view-search-bar#16]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0-beta1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [tree-view-search-bar](https://github.com/lixinliang/tree-view-search-bar) package 1.0.0

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '' is not a valid attribute name.

```
At /Users/trentgillham/.atom/packages/tree-view-search-bar/lib/views/app.vue:178

Error: Failed to execute 'setAttribute' on 'Element': '' is not a valid attribute name.
    at /packages/tree-view-search-bar/lib/views/app.vue:178:24)
    at /packages/tree-view-search-bar/node_modules/vue/dist/vue.js:193:12)
    at /packages/tree-view-search-bar/lib/views/app.vue:111:19)
```

### Commands

```
     -4:47.9.0 core:confirm (input.hidden-input)
     -4:40.3.0 editor:toggle-line-comments (input.hidden-input)
     -4:39.9.0 core:save (input.hidden-input)
     -4:34.1.0 core:copy (input.hidden-input)
     -4:33.5.0 project-find:show (input.hidden-input)
     -4:33 core:paste (input.hidden-input)
     -4:31.6.0 editor:newline (input.hidden-input)
     -4:30 core:undo (input.hidden-input)
     -4:29.2.0 core:confirm (input.hidden-input)
     -3:07.0 editor:toggle-line-comments (input.hidden-input)
     -3:06.5.0 core:save (input.hidden-input)
     -1:10.7.0 project-find:show (input.hidden-input)
     -1:10.3.0 core:paste (input.hidden-input)
     -1:09.9.0 core:confirm (input.hidden-input)
  3x -1:06.7.0 core:backspace (input.hidden-input)
     -1:04.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
ariake-dark-syntax 0.1.3 
atom-beautify 0.30.5 
atom-clock 0.1.15 
atom-easy-jsdoc 4.12.4 
atom-ide-ui 0.5.2 
atom-material-syntax 1.0.7 
atom-material-ui 2.0.6 
atomify 0.6.0 
autoclose-html 0.23.0 
busy-signal 1.4.3 
chameleon-ui 2.0.0 
color-picker 2.2.5 
css-snippets 1.1.0 
emmet 2.4.3 
expose 0.15.0 
file-icons 2.1.13 
fonts 3.0.3 
genesis-syntax 1.0.9 
glowing-cursor 0.1.2 
highlight-selected 0.13.1 
html-to-css 0.2.2 
ide-python 0.2.2 
ide-typescript 0.6.2 
imdone-atom 2.2.7 
intentions 1.1.5 
language-babel 2.76.1 
language-cypher 0.5.0 
language-typescript-grammars-only 1.6.0 
linter 2.2.0 
linter-eslint 8.4.0 
linter-less 2.6.0 
linter-ui-default 1.6.10 
livestyle-atom 0.2.10 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
nucleus-dark-ui 0.12.3 
oceanic-next 1.0.0 
pigments 0.40.2 
pristine-ui 1.1.10 
pure-syntax 0.3.0 
python-autopep8 0.1.3 
qolor 0.4.2 
react 0.16.2 
spacegray-light-syntax 0.1.0 
steam-pirate-ui 0.6.1 
sync-settings 0.8.3 
terminal-plus 0.14.5 
tree-view-search-bar 1.0.0 
```

**Comment by esl-douglas** [comment]
Same error on Ubuntu Linux.

**Comment by lixinliang** [comment]
Oh. I see. I will check later.

**Comment by jigglycrumb** [comment]
Same problem here, on Mac OS Sierra.

**Comment by matthias-ccri** [comment]
Problem still exists -- atom 1.25.0 x64 Ubuntu

**Comment by cvanelteren** [comment]
Is there any fix for this? Problem exists on antergos


Atom    : 1.32.2
Electron: 2.0.12
Chrome  : 61.0.3163.100
Node    : 8.9.3
