### ISSUE TITLE
Uncaught TypeError: Cannot read property 'editorElement' of undefined

### ISSUE THREAD

**Issue by motir** [lixinliang/tree-view-search-bar#8]
[Enter steps to reproduce:]

Can't easily reproduce, but this happened when I just hit ESC in the search bar (it was empty).
:-S

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [tree-view-search-bar](https://github.com/lixinliang/tree-view-search-bar) package 0.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'editorElement' of undefined

```
At C:\Users\Moti\.atom\packages\tree-view-search-bar\lib\view.js:111

TypeError: Cannot read property 'editorElement' of undefined
    at /packages/tree-view-search-bar/lib/view.js:111:84)
    at /packages/tree-view-search-bar/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at /packages/tree-view-search-bar/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  3x -2:16.4.0 core:backspace (input.hidden-input)
     -2:13.7.0 core:confirm (input.hidden-input)
     -2:03.8.0 core:backspace (input.hidden-input)
     -2:02.7.0 core:confirm (input.hidden-input)
     -0:18.4.0 core:select-all (input.hidden-input)
     -0:18.3.0 core:backspace (input.hidden-input)
     -0:17.4.0 editor:consolidate-selections (input.hidden-input)
     -0:17.4.0 tool-panel:unfocus (input.hidden-input)
     -0:08.3.0 editor:consolidate-selections (input.hidden-input)
     -0:08.3.0 tool-panel:unfocus (input.hidden-input)
     -0:06.9.0 editor:consolidate-selections (input.hidden-input)
     -0:06.9.0 tool-panel:unfocus (input.hidden-input)
     -0:06.4.0 editor:consolidate-selections (input.hidden-input)
     -0:06.4.0 tool-panel:unfocus (input.hidden-input)
     -0:04.7.0 editor:consolidate-selections (input.hidden-input)
     -0:04.7.0 tool-panel:unfocus (input.hidden-input)
```

### Non-Core Packages

```
atom-ctags 5.0.0 
project-view 0.6.1 
symbols-tree-view 0.13.2 
tree-view-autoresize 1.5.0 
tree-view-open-files 0.3.0 
tree-view-search-bar 0.1.2 
```

**Comment by lixinliang** [comment]
Fixed in `0.1.3`, Avoid throwing errors now.
